# version: '3.8'

services:
  mssql:
    container_name: mssql
    hostname: mssql
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8       # linux/arm64/v8 | linux/amd64
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD?MSSQL_SA_PASSWORD not set}
      - MSSQL_DATABASE=${MSSQL_DATABASE?MSSQL_DATABASE not set}
      - MSSQL_BACKUP=${MSSQL_BACKUP?MSSQL_BACKUP not set}
      - MSSQL_TELEMETRY_ENABLED=False
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
      - MSSQL_SLEEP=7
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
