# version: '3.8'

services:
  mssql:
    # image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8       # linux/arm64/v8 | linux/amd64
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD?MSSQL_SA_PASSWORD not set}
      - MSSQL_DATABASE=${MSSQL_DATABASE?MSSQL_DATABASE not set}
      - MSSQL_BACKUP=${MSSQL_BACKUP?MSSQL_BACKUP not set}
      - MSSQL_TELEMETRY_ENABLED=False
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
      - MSSQL_SLEEP=7
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
    # TODO: MSSQL_SA_PASSWORD isn't correctly setting the sa password
    # command: >
    #   bash -c '/usr/bin/sqlcmd \
    #     -S mssql \
    #     -U sa \
    #     -P $$MSSQL_SA_PASSWORD \
    #     -d tempdb \
    #     -q "EXIT(RESTORE DATABASE $$MSSQL_DATABASE FROM DISK = $$MSSQL_BACKUP)"; wait;'

  # sqlcmd:
  #   image: mcr.microsoft.com/mssql-tools:latest
  #   container_name: mssql-aw-sqlcmd
  #   platform: linux/amd64
  #   stdin_open: true
  #   environment:
  #     - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD?MSSQL_SA_PASSWORD not set}
  #     - MSSQL_DATABASE=${MSSQL_DATABASE?MSSQL_DATABASE not set}
  #     - MSSQL_BACKUP=${MSSQL_BACKUP?MSSQL_BACKUP not set}
  #   volumes:
  #     - ./data/backup:/var/opt/mssql/backup
  #   command: >
  #     bash -c '/opt/mssql-tools/bin/sqlcmd \
  #       -S mssql \
  #       -U sa \
  #       -P $$MSSQL_SA_PASSWORD \
  #       -d tempdb \
  #       -q "EXIT(RESTORE DATABASE $$MSSQL_DATABASE FROM DISK = $$MSSQL_BACKUP)"; wait;'
